---
- name: Search-only, return list of found updates
  hosts: winad
  gather_facts: false
  tasks:
    - name: Search-only, return list of found updates (if any), log to C:\ansible_updade.txt
      win_updates:
        category_names: SecurityUpdates
        state: searched
        log_path: C:\ansible_update.txt
